name: Documentation Build and Deploy CI

on:
  push:
    branches:
    - master
    paths:
    - 'docs/**'
    - '.github/workflows/docs.yml'

jobs:

  deploy-preview-docs:
    name: Deploy Documentation Preview
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Deploy Preview
      env:
        # Deploy to preview server
        DOCS_BUILD_DIR: "${CI_PROJECT_DIR}/docs/_build/"
        DOCS_DEPLOY_PRIVATEKEY: ${{ secrets.DOCS_KEY }}
        DOCS_DEPLOY_PATH: ${{ secrets.DOCS_PATH }}
        DOCS_DEPLOY_SERVER: ${{ secrets.DOCS_SERVER }}
        DOCS_DEPLOY_URL_BASE: ${{ secrets.DOCS_URL }}
        DOCS_DEPLOY_SERVER_USER: ${{ secrets.DOCS_USER }}
      run: |
        sudo apt update
        sudo apt install python3-pip python3-setuptools
        source ./docs/utils.sh
        add_doc_server_ssh_keys $DOCS_DEPLOY_PRIVATEKEY $DOCS_DEPLOY_SERVER $DOCS_DEPLOY_SERVER_USER
        export GIT_VER=$(git describe --always)
        echo "PIP install requirements..."
        pip3 install --user -r ./docs/requirements.txt
        echo "Building the Docs..."
        cd ./docs && build-docs -l en
        echo "Deploy the Docs..."
        deploy-docs
